openapi: 3.0.2
info:
  title: Subscription API
  description: >-
    API для процесса оформления подписки. Позволяет просматривать доступные
    подписки и переходить к оплате выбранного варианта.
  version: '1.0'
servers:
  - url: https://api.server.test/v1
security:
  - bearerAuth: []
tags:
  - name: subscriptions
    description: Информация о подписках
  - name: payments
    description: Оплата подписки
paths:
  /subscriptions:
    get:
      tags:
        - subscriptions
      summary: Получить список вариантов подписки
      responses:
        '200':
          description: Список подписок получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '404':
          description: Подписки не найдены
        '500':
          description: Внутренняя ошибка сервера
  /subscriptions/{subscriptionId}:
    get:
      tags:
        - subscriptions
      summary: Получить информацию о подписке
      description: Получение подробной информации о подписке.
      security:
        - bearerAuth: []
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор подписки
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор пользователя
      responses:
        '200':
          description: Информация о подписке получена
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Subscription'
                  - $ref: '#/components/schemas/SubscriptionStatus'
        '404':
          description: Подписка с указанным ID не найдена
        '500':
          description: Внутренняя ошибка сервера
  /payments:
    post:
      summary: Оформить оплату подписки
      description: Начать процесс оплаты подписки через внешнюю платежную систему.
      security:
        - bearerAuth: []
      tags:
        - payments
      parameters:
        - name: subscriptionId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор подписки, которую пользователь желает оплатить.
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Идентификатор пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: uuid
                subscriptionId:
                  type: string
                  format: uuid
      responses:
        '302':
          description: Переадресация на страницу оплаты
          headers:
            paymentAPI:
              description: URL для перенаправления на внешнюю платежную систему
              schema:
                type: string
                format: uri
  /payments/{paymentId}:
    get:
      summary: Проверить статус платежа
      description: Получить информацию о статусе платежа для подписки.
      security:
        - bearerAuth: []
      tags:
        - payments
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор платежа
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор пользователя
        - name: subscriptionId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор подписки
      responses:
        '200':
          description: Платеж успешно завершен, подписка оформлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionStatus'
        '404':
          description: Платеж не найден
        '408':
          description: Время ожидания запроса истекло
        '500':
          description: Внутренняя ошибка сервера
components:
  schemas:
    Subscription:
      description: Описание подписки
      type: object
      properties:
        subscriptionId:
          type: string
          description: Уникальный идентификатор подписки
          example: '12345'
        name:
          type: string
          description: Название подписки
          example: Базовая подписка
        type:
          type: string
          description: Тип подписки
          enum:
            - Basic
            - Pro
            - Premium
        price:
          type: number
          format: float
          description: Цена подписки
          example: 399.99
        duration:
          type: string
          description: Длительность подписки (например, "1 месяц", "1 год")
          example: 1 месяц
    SubscriptionStatus:
      description: Статус подписки
      type: object
      properties:
        active:
          type: boolean
          description: Статус активности подписки
          example: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
